{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Product defects","children":[{"name":"Timed out retrying after 10000ms: Expected to find content: 'This is the container App hosted at localhost:8080' within the element: <div.container> but never did.\n\nThe command was expected to run against origin `http://localhost:8080` but the application is at origin `about://blank`.\n\nThis commonly happens when you have either not navigated to the expected origin or have navigated away unexpectedly.","children":[{"name":"Check Host This is the container App hosted at localhost:8080 UI and Invoices, Expenses buttons","uid":"b0a077fa7fd009c","parentUid":"5bd9bac1fcef4e96ce654d6f1d270c76","status":"failed","time":{"start":1682964287462,"stop":1682964297988,"duration":10526},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":false,"parameters":[]}],"uid":"5bd9bac1fcef4e96ce654d6f1d270c76"},{"name":"The following error originated from your application code, not from Cypress.\n\n  > Loading script failed.\n(error: http://localhost:3001/static/remoteEntry.js)\nwhile loading \"./Content\" from 3476\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","children":[{"name":"Check App headers and buttons visability","uid":"4830f8bf09240cff","parentUid":"d4099bc60e9a507497decebf840ff6f7","status":"failed","time":{"start":1682965879599,"stop":1682965880285,"duration":686},"flaky":true,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":6,"retriesStatusChange":true,"parameters":[]},{"name":"Check that App 2 Content Block with filled text appear","uid":"4bd351420ce55926","parentUid":"d4099bc60e9a507497decebf840ff6f7","status":"failed","time":{"start":1682965880809,"stop":1682965881327,"duration":518},"flaky":true,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":6,"retriesStatusChange":true,"parameters":[]}],"uid":"d4099bc60e9a507497decebf840ff6f7"},{"name":"`cy.visit()` failed because you are attempting to visit a URL that is of a different origin.\n\nYou likely forgot to use `cy.origin()`:\n\n`cy.visit('http://localhost:3002/')`\n`<commands targeting http://localhost:3002 go here>`\n\n`cy.origin('http://localhost:3001', () => {`\n`  cy.visit('http://localhost:3001/')`\n`  <commands targeting http://localhost:3001 go here>`\n`})`\n\nThe new URL is considered a different origin because the following parts of the URL are different:\n\n  > port\n\nYou may only `cy.visit()` same-origin URLs within a single test.\n\nThe previous URL you visited was:\n\n  > 'http://localhost:3002'\n\nYou're attempting to visit this URL:\n\n  > 'http://localhost:3001'\n\nhttps://on.cypress.io/cannot-visit-different-origin-domain","children":[{"name":"Check Apps share div with React version 16.14.0","uid":"1d5801f229762e1d","parentUid":"79d9ce04e5b4b4fb854060ab466e5da9","status":"failed","time":{"start":1682965903028,"stop":1682965903621,"duration":593},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":1,"retriesStatusChange":false,"parameters":[]}],"uid":"79d9ce04e5b4b4fb854060ab466e5da9"},{"name":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_1__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","children":[{"name":"Checks that base link set to app 1","uid":"7080b68cef1f111","parentUid":"a53062f8c5adb92dbed2b700edf10685","status":"failed","time":{"start":1682966993019,"stop":1682966993021,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":3,"retriesStatusChange":false,"parameters":[]},{"name":"Checks base page message & clicks each link by text & checks changes in page message and url & check reload does not revert changes","uid":"802c386b5859ede4","parentUid":"a53062f8c5adb92dbed2b700edf10685","status":"failed","time":{"start":1682966993021,"stop":1682966993022,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":3,"retriesStatusChange":false,"parameters":[]},{"name":"Checks all texted links visibility","uid":"8144e3af98a614f6","parentUid":"a53062f8c5adb92dbed2b700edf10685","status":"failed","time":{"start":1682966993021,"stop":1682966993021,"duration":0},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":3,"retriesStatusChange":false,"parameters":[]}],"uid":"a53062f8c5adb92dbed2b700edf10685"},{"name":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > (0 , react_router_dom__WEBPACK_IMPORTED_MODULE_0__.createBrowserRouter) is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","children":[{"name":"Checks page message visibility","uid":"ee53dcd5a24c26e6","parentUid":"d0a8a86d331275ad88790af97f7763f8","status":"failed","time":{"start":1682966994397,"stop":1682966995392,"duration":995},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":5,"retriesStatusChange":false,"parameters":[]},{"name":"Checks texted link visibility","uid":"287d44dfc650e036","parentUid":"d0a8a86d331275ad88790af97f7763f8","status":"failed","time":{"start":1682966996233,"stop":1682966997168,"duration":935},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":5,"retriesStatusChange":false,"parameters":[]},{"name":"Checks that on click on link url texts on page changed & changes is not reverted after reload","uid":"dbdbfa990dd78e5","parentUid":"d0a8a86d331275ad88790af97f7763f8","status":"failed","time":{"start":1682966997991,"stop":1682966998868,"duration":877},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":5,"retriesStatusChange":false,"parameters":[]}],"uid":"d0a8a86d331275ad88790af97f7763f8"},{"name":"The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.\n\n  > ReactDOM.createRoot is not a function\n\nWhen Cypress detects uncaught errors originating from your application it will automatically fail the current test.\n\nThis behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.\n\nhttps://on.cypress.io/uncaught-exception-from-application","children":[{"name":"Checks that host card button text includes counter which changed after click & check value reverted after reload","uid":"402585e3ad75ec44","parentUid":"d933a6ac0b4f64a2d8830e4490c1bfef","status":"failed","time":{"start":1682967664075,"stop":1682967665204,"duration":1129},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":2,"retriesStatusChange":true,"parameters":[]},{"name":"Checks that remote card button text includes counter which changed after click & check value reverted after reload","uid":"eca55b9e8bd235c0","parentUid":"d933a6ac0b4f64a2d8830e4490c1bfef","status":"failed","time":{"start":1682967666190,"stop":1682967667616,"duration":1426},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":2,"retriesStatusChange":true,"parameters":[]}],"uid":"d933a6ac0b4f64a2d8830e4490c1bfef"}],"uid":"8fb3a91ba5aaf9de24cc8a92edc82b5d"},{"name":"Test defects","children":[{"name":"`cy.visit()` failed trying to load:\n\nhttp://localhost:8081/\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  > Error: connect ECONNREFUSED 127.0.0.1:8081\n\nCommon situations why this would fail:\n  - you don't have internet access\n  - you forgot to run / boot your web server\n  - your web server isn't accessible\n  - you have weird network configuration settings on your computer","children":[{"name":"Check Host This is the Remote App hosted at localhost:8081) UI and Invoices, Expenses buttons","uid":"3bc3ccea590af568","parentUid":"53f6821ed2d032041c9d946c83fe4dd0","status":"broken","time":{"start":1682964299021,"stop":1682964299022,"duration":1},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[]}],"uid":"53f6821ed2d032041c9d946c83fe4dd0"},{"name":"`cy.visit()` failed trying to load:\n\nhttp://localhost:3001/\n\nWe attempted to make an http request to this URL but the request failed without a response.\n\nWe received this error at the network level:\n\n  > Error: connect ECONNREFUSED 127.0.0.1:3001\n\nCommon situations why this would fail:\n  - you don't have internet access\n  - you forgot to run / boot your web server\n  - your web server isn't accessible\n  - you have weird network configuration settings on your computer","children":[{"name":"Check App elements visability","uid":"1ea5b90b8f0e5b71","parentUid":"898e08c9ea3114d3e46344ff31728145","status":"broken","time":{"start":1682965882280,"stop":1682965883227,"duration":947},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":4,"retriesStatusChange":true,"parameters":[]}],"uid":"898e08c9ea3114d3e46344ff31728145"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}